### ISSUE TITLE
Harmonise code formatting and contributing section

### ISSUE THREAD

**Issue by epiben** [heli-xu/findSVI#19]
Dear @heli-xu,

I've been assigned as JOSS reviewer and would like to get started, so I'll be posting comments and suggestions here as per JOSS recommendations. To keep things atomic, I'll raise one thing per issue.

Might I suggest you use automatic styling of the code? Currently, the style is relatively heterogeneous, which makes it more tricky to follow the logic. I'd suggest simply running `styler:::style_active_pkg()`. One might even consider adding this as a pre-commit hook.

Cheers
Ben

**Comment by heli-xu** [comment]
Hi Ben,

Thank you for agreeing to review our paper and for your suggestion! We'll plan to add a pre-commit hook for this.

-Heli

**Comment by heli-xu** [comment]
Linking the JOSS review comment from @epiben for reference: https://github.com/openjournals/joss-reviews/issues/6525#issuecomment-2143985739

**Comment by heli-xu** [comment]
Thanks again for reviewing the paper @epiben . We'll think about the testing strategy in the future release.
