### ISSUE TITLE
Update for 2022

### ISSUE THREAD

**Issue by hschoi11** [heli-xu/findSVI#20]
Could you please update for 2022 data sources?
The 2022 data is available now.

**Comment by heli-xu** [comment]
Hi! Thanks for your interest. We're working on that!

**Comment by heli-xu** [comment]
Hi, the 2022 data is now available if you install the development version from github. There is also a new feature to support SVI calculation at customized geographic levels (for details please see #22). We would appreciate any feedback and suggestions!
