### ISSUE TITLE
state default NULL vs 'US'

### ISSUE THREAD

**Issue by ran-codes** [heli-xu/findSVI#5]
I think the behavior state = NULL or default state of the warpper + get_data() is a little unintuitive. Two things that could be improvements IMO:

- if state is missing I think it should return an error (e.g. please enter a valid state or if you want US then state = 'US'). I think by defaulting to US it cause a rather long funciton call.... and I don't think its too much work to ask people toinput state = "US". 
- its not explicitly clear that NULL  = "US". So I think rather than using NULL to represent US; the explicit value of US would be better.

**Comment by heli-xu** [comment]
As `state = NULL` is following the behavior of `tidycensus::get_acs()`, I'll keep this default for now to make it easier for people that are used to tidycensus.  But I agree it's more intuitive to use `state = 'US'`, so this option is also included in `find_svi()` and `get_census_data()`, and will be evaluated as the default.

**Comment by ran-codes** [comment]
>tidycensus::get_acs(), I'll keep this default for now to make it easier for people that are used to tidycensus 

makes sense! Agreed, just keep however tidyCensus() work!
