### ISSUE TITLE
rename summarise_svi() to find_svi()

### ISSUE THREAD

**Issue by ran-codes** [heli-xu/findSVI#6]
just a suggestion for two reasons:

- package name is findSVI, hehe I think its  appropriate to have a function called find_svi().
- also summarise_svi() is harder to type -.- compared to find_svi()

**Comment by heli-xu** [comment]
makes sense...I renamed it to find_svi(). I didn't love summarise_svi() very much, but wanted to make it easier for people to tell it apart from get_svi().

**Comment by ran-codes** [comment]
works. great. small suggestion is to update to introduce find_svi() first (as most users will use that) rather than get_data and calcualte_svi() separately. Other than that looks fantastic!!
