### ISSUE TITLE
journal target 

### ISSUE THREAD

**Issue by ran-codes** [heli-xu/findSVI#8]
https://joss.theoj.org/ is a good option for first submission

**Comment by ran-codes** [comment]
[rr2: An R package to calculate R2 s for regression models](https://joss.theoj.org/papers/10.21105/joss.01028)
2 paragraphs. 
On CRAN

**Comment by heli-xu** [comment]
a delayed documentation of timeline...
submission to JOSS 3/4/24
editor first contact 3/17/24
2 reviewers assigned 3/22/24
review issue on  JOSS repo: https://github.com/openjournals/joss-reviews/issues/6525#issuecomment-2015420220

**Comment by heli-xu** [comment]
🎉 The paper is accepted ([link](https://joss.theoj.org/papers/10.21105/joss.06525))! @ran-codes @usamabilal
Thank you very much for your help and support!!

**Comment by ran-codes** [comment]
🍰 🍰 🍰 🍰 🍰 🍰 🍰 🍰 🍰 🍰 🍰 🍰 🍰 🍰 🍰 🍰 🍰 🍰 🍰 🍰 🍰 🍰 🍰 🍰 🍰 🍰 🍰 🍰 🍰 🍰 🍰 🍰 🍰 🍰 🍰 🍰 🍰 🍰 🍰 🍰 🍰 🍰 🍰 🍰 🍰 🍰 🍰 🍰 🍰 🍰 🍰 🍰 🍰 🍰 🍰 🍰 🍰 🍰 🍰 🍰 🍰 🍰 🍰 🍰 🍰 🍰 🍰 🍰 🍰 🍰 🍰 🍰 🍰 🍰 🍰 🍰 🍰 🍰 🍰 🍰 🍰 🍰 🍰 🍰 🍰 🍰 🍰 🍰 🍰 🍰 🍰 🍰 🍰 🍰 🍰 🍰 🍰 🍰 🍰 🍰 🍰 🍰 🍰 🍰 🍰 🍰 🍰 🍰 🍰 🍰 🍰 🍰 🍰 🍰 🍰 🍰 🍰 🍰 🍰 🍰 🍰 🍰 🍰 🍰 🍰 🍰 🍰 🍰 🍰 🍰 🍰 🍰 🍰 🍰 🍰 🍰 🍰 🍰 🍰 🍰 🍰 🍰 🍰 🍰 🍰 🍰 🍰 🍰 🍰 🍰 🍰 🍰 🍰 🍰 🍰 🍰 🍰 🍰 🍰 🍰 🍰 🍰 🍰 🍰 🍰 🍰 🍰 🍰 🍰 🍰 🍰 🍰 🍰 🍰 🍰 🍰 🍰 🍰 🍰 🍰 🍰 🍰 🍰 🍰 🍰 🍰 🍰 🍰 🍰 🍰 🍰 🍰 🍰 🍰 🍰 🍰 🍰 🍰 🍰 🍰 🍰 🍰 🍰 🍰 🍰 🍰 🍰 🍰 🍰
